/** IMPORTANTE, EJECUTAR CON EL USUARIO ROLSAC  **/
GRANT SELECT ON RSC_TAXA TO ROLSAC2;
GRANT SELECT ON RSC_TRATAX TO ROLSAC2;
GRANT SELECT ON RSC_TAXA TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRATAX TO WWW_ROLSAC2;


