/** IMPORTANTE, EJECUTAR CON EL USUARIO WWW_ROLSAC2 **/
CREATE OR REPLACE SYNONYM RS2_PRCTAX FOR "ROLSAC2"."RS2_PRCTAX";
CREATE OR REPLACE SYNONYM RS2_TRAPRTX FOR "ROLSAC2"."RS2_TRAPRTX";
CREATE OR REPLACE SYNONYM RS2_PRCTAX_SEQ    FOR ROLSAC2.RS2_PRCTAX_SEQ;
CREATE OR REPLACE SYNONYM RS2_TRAPRTX_SEQ    FOR ROLSAC2.RS2_TRAPRTX_SEQ;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TAXAS FOR ROLSAC.RSC_TAXA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TAXAS_TRAD FOR ROLSAC.RSC_TRATAX;
CREATE OR REPLACE SYNONYM RS2_IDPDU_SEQ    FOR "ROLSAC2"."RS2_IDPDU_SEQ";
CREATE OR REPLACE SYNONYM RS2_CATPDU_SEQ    FOR ROLSAC2.RS2_CATPDU_SEQ;
CREATE OR REPLACE SYNONYM RS2_TRACPDU_SEQ    FOR ROLSAC2.RS2_TRACPDU_SEQ;
CREATE OR REPLACE SYNONYM RS2_IDPDU  FOR "ROLSAC2"."RS2_IDPDU";
CREATE OR REPLACE SYNONYM RS2_CATPDU  FOR "ROLSAC2"."RS2_CATPDU";
CREATE OR REPLACE SYNONYM RS2_TRACPDU  FOR "ROLSAC2"."RS2_TRACPDU";