/** IMPORTANTE, EJECUTAR CON EL USUARIO ROLSAC  **/
GRANT SELECT ON RSC_TAXA TO ROLSAC2;
GRANT SELECT ON RSC_TRATAX TO ROLSAC2;
GRANT SELECT ON RSC_TAXA TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRATAX TO WWW_ROLSAC2;



/** IMPORTANTE, EJECUTAR CON EL USUARIO ROLSAC2 **/
ALTER TABLE RS2_PRCWF
DROP COLUMN PRWF_SVTASA;
CREATE SEQUENCE "RS2_PRCTAX_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "RS2_PRCTAX"
(
	"PRTX_CODIGO"  NUMBER(10) NOT NULL,          -- CODIGO
	"PRTX_CODPRWF" NUMBER(10) NOT NULL          -- CODIGO PROC WF
) TABLESPACE ROLSAC2_DADES;
GRANT SELECT, INSERT, UPDATE, DELETE ON "RS2_PRCTAX" TO WWW_ROLSAC2;
GRANT SELECT ON "RS2_PRCTAX_SEQ" TO WWW_ROLSAC2;
CREATE SEQUENCE "RS2_TRAPRTX_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "RS2_TRAPRTX"
(
	"TRTX_CODIGO"        NUMBER(10) NOT NULL,       -- CODIGO
	"TRTX_CODPRTX"      NUMBER(10) NOT NULL,       -- CODIGO TAXA
	"TRTX_IDIOMA"         VARCHAR2(2 CHAR) NOT NULL, -- IDIOMA
	"TRTX_IDENTI"          VARCHAR2(256 CHAR) NOT NULL,                 -- IDENTIFICADOR (O CODIGO EN LA PARTE VISUAL)
	"TRTX_DESCRI"         VARCHAR2(4000 CHAR) NULL,   -- DESCRIPCION
	"TRTX_FORPAG"       VARCHAR2(4000 CHAR) NULL,  -- FORMA DE PAGAMENT
	"TRTX_URL"              VARCHAR2(1000 CHAR) NULL  -- URL
) TABLESPACE ROLSAC2_DADES;
GRANT SELECT, INSERT, UPDATE, DELETE ON "RS2_TRAPRTX" TO WWW_ROLSAC2;
GRANT SELECT ON "RS2_TRAPRTX_SEQ" TO WWW_ROLSAC2;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TAXAS FOR ROLSAC.RSC_TAXA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TAXAS_TRAD FOR ROLSAC.RSC_TRATAX;
GRANT SELECT ON "RS2_IDPDU_SEQ" TO WWW_ROLSAC2;
GRANT SELECT ON "RS2_CATPDU_SEQ" TO WWW_ROLSAC2;
GRANT SELECT ON "RS2_TRACPDU_SEQ" TO WWW_ROLSAC2;


/** IMPORTANTE, EJECUTAR CON EL USUARIO WWW_ROLSAC2 **/
CREATE OR REPLACE SYNONYM RS2_PRCTAX FOR "ROLSAC2"."RS2_PRCTAX";
CREATE OR REPLACE SYNONYM RS2_TRAPRTX FOR "ROLSAC2"."RS2_TRAPRTX";
CREATE OR REPLACE SYNONYM RS2_PRCTAX_SEQ    FOR ROLSAC2.RS2_PRCTAX_SEQ;
CREATE OR REPLACE SYNONYM RS2_TRAPRTX_SEQ    FOR ROLSAC2.RS2_TRAPRTX_SEQ;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TAXAS FOR ROLSAC.RSC_TAXA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TAXAS_TRAD FOR ROLSAC.RSC_TRATAX;
CREATE OR REPLACE SYNONYM RS2_IDPDU_SEQ    FOR "ROLSAC2"."RS2_IDPDU_SEQ";
CREATE OR REPLACE SYNONYM RS2_CATPDU_SEQ    FOR ROLSAC2.RS2_CATPDU_SEQ;
CREATE OR REPLACE SYNONYM RS2_TRACPDU_SEQ    FOR ROLSAC2.RS2_TRACPDU_SEQ;