/*Insert de plataformas de tramitación*/

Insert into RS2_PLATRE (PTTR_CODIGO, PTTR_CODENTI, PTTR_IDENTI)
values (RS2_PLATRE_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'SISTRA2');
Insert into RS2_TRAPLATRE (TRPT_CODIGO, TRPT_CODPTTR, TRPT_IDIOMA, TRPT_URL, TRPT_DESCR)
values (RS2_TRAPTTR_SEQ.NEXTVAL, RS2_PLATRE_SEQ.CURRVAL, 'ca',
        'https://ibter.indra.es/sistramitfront/asistente/iniciarTramite.html',
        'Assistent de tramitació SISTRA2');
Insert into RS2_TRAPLATRE (TRPT_CODIGO, TRPT_CODPTTR, TRPT_IDIOMA, TRPT_URL, TRPT_DESCR)
values (RS2_TRAPTTR_SEQ.NEXTVAL, RS2_PLATRE_SEQ.CURRVAL, 'es',
        'https://ibter.indra.es/sistramitfront/asistente/iniciarTramite.html',
        'Asistente de tramitación SISTRA2');

Insert into RS2_PLATRE (PTTR_CODIGO, PTTR_CODENTI, PTTR_IDENTI)
values (RS2_PLATRE_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'SISTRA1');

Insert into RS2_TRAPLATRE (TRPT_CODIGO, TRPT_CODPTTR, TRPT_IDIOMA, TRPT_URL, TRPT_DESCR)
values (RS2_TRAPTTR_SEQ.NEXTVAL, RS2_PLATRE_SEQ.CURRVAL, 'ca',
        'https://ibter.indra.es/sistrafront/inicio?language=ca',
        'Assistent de tramitació SISTRA1');
Insert into RS2_TRAPLATRE (TRPT_CODIGO, TRPT_CODPTTR, TRPT_IDIOMA, TRPT_URL, TRPT_DESCR)
values (RS2_TRAPTTR_SEQ.NEXTVAL, RS2_PLATRE_SEQ.CURRVAL, 'es',
        'https://ibter.indra.es/sistrafront/inicio?language=es',
        'Asistente de tramitación SISTRA1');

/*Insert de temas*/

Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('141', RS2_ENTIDA_SEQ.CURRVAL, 'MEDI_AMBIENT', null, null);
Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('143', RS2_ENTIDA_SEQ.CURRVAL, 'PESCA', '141', '141');
Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('142', RS2_ENTIDA_SEQ.CURRVAL, 'CAZA', '141', '141');
Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('144', RS2_ENTIDA_SEQ.CURRVAL, 'AGRICULTURA', '141', '141');
Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('145', RS2_ENTIDA_SEQ.CURRVAL, 'ANIMALS', '141', '141');
Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('146', RS2_ENTIDA_SEQ.CURRVAL, 'CULTURA', null, null);
Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('147', RS2_ENTIDA_SEQ.CURRVAL, 'MUSICA', '146', '146');
Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('148', RS2_ENTIDA_SEQ.CURRVAL, 'POESIA', '146', '146');
Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('149', RS2_ENTIDA_SEQ.CURRVAL, 'LITERATURA', '146', '146');
Insert into RS2_TEMA (TEMA_CODIGO, TEMA_CODENTI, TEMA_IDENTI, TEMA_PADRE, TEMA_MATHPATH)
values ('150', RS2_ENTIDA_SEQ.CURRVAL, 'LLENGUA', '146', '146');

Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('201', '141', 'ca', 'Medi Ambient');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('202', '141', 'es', 'Medio Ambiente');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('204', '142', 'es', 'Caza');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('205', '143', 'ca', 'Pesca');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('203', '142', 'ca', 'Caça');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('206', '143', 'es', 'Pesca');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('207', '144', 'ca', 'Agricultura');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('208', '144', 'es', 'Agricultura');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('209', '145', 'ca', 'Animals de companyia');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('210', '145', 'es', 'Animales de compañía');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('211', '146', 'ca', 'Cultura');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('212', '146', 'es', 'Cultura');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('213', '147', 'ca', 'Música');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('214', '147', 'es', 'Música');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('215', '148', 'ca', 'Poesia');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('216', '148', 'es', 'Poesia');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('217', '149', 'ca', 'Literatura');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('218', '149', 'es', 'Literatura');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('219', '150', 'ca', 'Llengua');
Insert into RS2_TRATEMA (TRTE_CODIGO, TRTE_CODTEMA, TRTE_IDIOMA, TNTR_DESCR)
values ('220', '150', 'es', 'Lengua');

/*Insert de tipo de legitimación*/
Insert into RS2_TIPOLEG (TPLE_CODIGO, TPLE_IDENTI, TPLE_DEFECT)
values (RS2_TIPOLEG_SEQ.NEXTVAL, 'EJER_PODERES_PUB', '0');

Insert into RS2_TRATPLE (TRTL_CODIGO, TRTL_CODTPLE, TRTL_IDIOMA, TRTL_DESCRI)
values (RS2_TRATPLE_SEQ.NEXTVAL, RS2_TIPOLEG_SEQ.CURRVAL, 'ca', 'Exercici de poders públics');
Insert into RS2_TRATPLE (TRTL_CODIGO, TRTL_CODTPLE, TRTL_IDIOMA, TRTL_DESCRI)
values (RS2_TRATPLE_SEQ.NEXTVAL, RS2_TIPOLEG_SEQ.CURRVAL, 'es', 'Ejercicio de poderes públicos');

/*Insert de tipo afectación */
Insert into RS2_TIPOAFE (TPAN_CODIGO, TPAN_IDENTI)
values (RS2_TIPOAFE_SEQ.NEXTVAL, 'CERR');

Insert into RS2_TRATPAN (TRTA_CODIGO, TRTA_CODTPAN, TRTA_IDIOMA, TRTA_DESCRI)
values (RS2_TRATPAN_SEQ.NEXTVAL, RS2_TIPOAFE_SEQ.CURRVAL, 'ca', 'Correcció d''errors');
Insert into RS2_TRATPAN (TRTA_CODIGO, TRTA_CODTPAN, TRTA_IDIOMA, TRTA_DESCRI)
values (RS2_TRATPAN_SEQ.NEXTVAL, RS2_TIPOAFE_SEQ.CURRVAL, 'es', 'Corrección de errores');

/*Insert de tipo procedimiento*/
Insert into RS2_TIPOPRO (TPPR_CODIGO, TPPR_CODENTI, TPPR_IDENTI)
values (RS2_TIPOPRO_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'CONV');
Insert into RS2_TRATPPR (TRTP_CODIGO, TRTP_CODTPPR, TRTP_IDIOMA, TRTP_DESCR)
values (RS2_TRATPPR_SEQ.NEXTVAL, RS2_TIPOPRO_SEQ.CURRVAL, 'ca', 'Convocatòries');
Insert into RS2_TRATPPR (TRTP_CODIGO, TRTP_CODTPPR, TRTP_IDIOMA, TRTP_DESCR)
values (RS2_TRATPPR_SEQ.NEXTVAL, RS2_TIPOPRO_SEQ.CURRVAL, 'es', 'Convocatorias');

Insert into RS2_TIPOPRO (TPPR_CODIGO, TPPR_CODENTI, TPPR_IDENTI)
values (RS2_TIPOPRO_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'ALT');

Insert into RS2_TRATPPR (TRTP_CODIGO, TRTP_CODTPPR, TRTP_IDIOMA, TRTP_DESCR)
values (RS2_TRATPPR_SEQ.NEXTVAL, RS2_TIPOPRO_SEQ.CURRVAL, 'ca', 'Altres');
Insert into RS2_TRATPPR (TRTP_CODIGO, TRTP_CODTPPR, TRTP_IDIOMA, TRTP_DESCR)
values (RS2_TRATPPR_SEQ.NEXTVAL, RS2_TIPOPRO_SEQ.CURRVAL, 'es', 'Otros');

/*Insert de tipo de público objetivo*/
Insert into RS2_TIPOPUB (TPPO_CODIGO, TPPO_IDENTI, TPPO_EMPPUB)
values (RS2_TIPOPUB_SEQ.NEXTVAL, 'EMPUB', '1');
Insert into RS2_TRATPPO (TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
values (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'ca', 'Empleat públic');
Insert into RS2_TRATPPO (TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
values (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'es', 'Empleado público');

Insert into RS2_TIPOPUB (TPPO_CODIGO, TPPO_IDENTI, TPPO_EMPPUB)
values (RS2_TIPOPUB_SEQ.NEXTVAL, 'PERS', '0');
Insert into RS2_TRATPPO (TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
values (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'ca', 'Persones');
Insert into RS2_TRATPPO (TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
values (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'es', 'Personas');

/*Inset de tipo de UA*/
Insert into RS2_TIPOUNA (TPUA_CODIGO, TPUA_CODENTI, TPUA_IDENTI)
values (RS2_TIPOUNA_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'SECAUT');
Insert into RS2_TRATPUA (TRTU_CODIGO, TRTU_CODTPUA, TRTU_IDIOMA, TRTU_DESCRI, TRTU_CRGMAS, TRTU_CRGFEM, TRTU_TRCMAS,
                         TRTU_TRCFEM)
values (RS2_TRATPUA_SEQ.NEXTVAL, RS2_TIPOUNA_SEQ.CURRVAL, 'ca', 'Secretaria autonòmica', 'Secretari autonòmic', 'Sr.',
        'Secretària autonòmica', 'Sra.');
Insert into RS2_TRATPUA (TRTU_CODIGO, TRTU_CODTPUA, TRTU_IDIOMA, TRTU_DESCRI, TRTU_CRGMAS, TRTU_CRGFEM, TRTU_TRCMAS,
                         TRTU_TRCFEM)
values (RS2_TRATPUA_SEQ.NEXTVAL, RS2_TIPOUNA_SEQ.CURRVAL, 'es', 'Secretaria autonómica', 'Secretario autonomico', 'Sr.',
        'Secretaria autonómica', 'Sra.');


/*Insert de tipo via*/
Insert into RS2_TIPOVIA (TPVI_CODIGO, TPVI_IDENTI)
values (RS2_TIPOVIA_SEQ.NEXTVAL, 'VIA');

Insert into RS2_TRATPVI (TRTV_CODIGO, TRTV_CODTPVI, TRTV_IDIOMA, TRTV_DESCRI)
values (RS2_TRATPVI_SEQ.NEXTVAL, RS2_TIPOVIA_SEQ.CURRVAL, 'ca', ' C/ Gremi de Corredors, 10 (Polígon Son Rossinyol)');
Insert into RS2_TRATPVI (TRTV_CODIGO, TRTV_CODTPVI, TRTV_IDIOMA, TRTV_DESCRI)
values (RS2_TRATPVI_SEQ.NEXTVAL, RS2_TIPOVIA_SEQ.CURRVAL, 'es', ' C/ Gremi de Corredors, 10 (Polígon Son Rossinyol)');

/*Insert de tipo legitimación */
Insert into RS2_TIPOLEG (TPLE_CODIGO, TPLE_IDENTI, TPLE_DEFECT)
values (RS2_TIPOLEG_SEQ.NEXTVAL, 'EJER_PODERES_PUB', '0');

Insert into RS2_TRATPLE (TRTL_CODIGO, TRTL_CODTPLE, TRTL_IDIOMA, TRTL_DESCRI)
values (RS2_TRATPLE_SEQ.NEXTVAL, RS2_TIPOLEG_SEQ.CURRVAL, 'ca', 'Exercici de poders públics');
Insert into RS2_TRATPLE (TRTL_CODIGO, TRTL_CODTPLE, TRTL_IDIOMA, TRTL_DESCRI)
values (RS2_TRATPLE_SEQ.NEXTVAL, RS2_TIPOLEG_SEQ.CURRVAL, 'es', 'Ejercicio de poderes públicos');


/*Insert de tipo materia SIA*/
Insert into RS2_TIPOMSI (TPMS_CODIGO, TPMS_IDENTI)
values (RS2_TIPOMSI_SEQ.NEXTVAL, 'AGRICULTURA');
Insert into RS2_TRATPMS (TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
values (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Agricultura');
Insert into RS2_TRATPMS (TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
values (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Agricultura');

Insert into RS2_TIPOMSI (TPMS_CODIGO, TPMS_IDENTI)
values (RS2_TIPOMSI_SEQ.NEXTVAL, 'CANVICLI');
Insert into RS2_TRATPMS (TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
values (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Canvi climàtic');
Insert into RS2_TRATPMS (TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
values (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Cambio climático');

/*Insert de tipo forma de inicio*/
Insert into RS2_TIPOFOI (TPFI_CODIGO, TPFI_IDENTI)
values (RS2_TIPOFOI_SEQ.NEXTVAL, 'INPART');
Insert into RS2_TRATPFI (TRTF_CODIGO, TRTF_CODTPFI, TRTF_IDIOMA, TRTF_DESCRI)
values (RS2_TRATPFI_SEQ.NEXTVAL, RS2_TIPOFOI_SEQ.CURRVAL, 'ca', 'Instància de part');
Insert into RS2_TRATPFI (TRTF_CODIGO, TRTF_CODTPFI, TRTF_IDIOMA, TRTF_DESCRI)
values (RS2_TRATPFI_SEQ.NEXTVAL, RS2_TIPOFOI_SEQ.CURRVAL, 'es', 'Instancia de parte');

Insert into RS2_TIPOFOI (TPFI_CODIGO, TPFI_IDENTI)
values (RS2_TIPOFOI_SEQ.NEXTVAL, 'INPARTOFI');
Insert into RS2_TRATPFI (TRTF_CODIGO, TRTF_CODTPFI, TRTF_IDIOMA, TRTF_DESCRI)
values (RS2_TRATPFI_SEQ.NEXTVAL, RS2_TIPOFOI_SEQ.CURRVAL, 'ca', 'Instancia de part o d''ofici');
Insert into RS2_TRATPFI (TRTF_CODIGO, TRTF_CODTPFI, TRTF_IDIOMA, TRTF_DESCRI)
values (RS2_TRATPFI_SEQ.NEXTVAL, RS2_TIPOFOI_SEQ.CURRVAL, 'es', 'Instancia de parte o de oficio');

/*Insert tipo silencio administrativo*/

Insert into RS2_TIPOSAD (TPSA_CODIGO,TPSA_IDENTI) values (RS2_TIPOSAD_SEQ.NEXTVAL,'SADM');
Insert into RS2_TRATPSA (TRTS_CODIGO,TRTS_CODTPSA,TRTS_IDIOMA,TRTS_DESCRI) values (RS2_TRATPSA_SEQ.NEXTVAL,RS2_TIPOSAD_SEQ.CURRVAL,'ca','Silenci administratiu');
Insert into RS2_TRATPSA (TRTS_CODIGO,TRTS_CODTPSA,TRTS_IDIOMA,TRTS_DESCRI) values (RS2_TRATPSA_SEQ.NEXTVAL,RS2_TIPOSAD_SEQ.CURRVAL,'es','Silencio Administrativo');
Insert into RS2_TIPOSAD (TPSA_CODIGO,TPSA_IDENTI) values (RS2_TIPOSAD_SEQ.NEXTVAL,'TEL');
Insert into RS2_TRATPSA (TRTS_CODIGO,TRTS_CODTPSA,TRTS_IDIOMA,TRTS_DESCRI) values (RS2_TRATPSA_SEQ.NEXTVAL,RS2_TIPOSAD_SEQ.CURRVAL,'ca','Per telèfon');
Insert into RS2_TRATPSA (TRTS_CODIGO,TRTS_CODTPSA,TRTS_IDIOMA,TRTS_DESCRI) values (RS2_TRATPSA_SEQ.NEXTVAL,RS2_TIPOSAD_SEQ.CURRVAL,'es','Por teléfono');
