# Propietats de configuracio de rolsac2.
# La ubicacio d'aquest fitxer s'ha de registrar mitjan�ant la propietat de sistema
# es.caib.rolsac2.properties (veure apartat 3.5.2 dels estandards)
# (el fitxer empra la codificacio UTF-8)

## BACKEND START

#Propiedad para almacenamiento de ficheros ROLSAC2
ficherosExternos.path=S:\\files_rs2

#Propiedad para almacenamiento de ficheros de ROLSAC1 (cuando se realiza la migracion de ROLSAC1 a ROLSAC2)
ficherosRolsac1.path=S:\\files_rolsac1

#Propiedades para gestion procesos automaticos
#Expresion cron maestra (configurado para ejecutarse cada 30 min)
procesos.automaticos.cron=0 */30 * * *

#Tiempo maximo que esperaran las otras instancias en caso de que la instancia maestro no ejecute los procesos
procesos.minMaxMaestroInactivo=15

# Literales cuando se realiza una accion en el flujo.
# Este apartado podra ir por configuracion global
es.caib.rolsac2.procServ.accion.PV.es=Se solicita la publicaci\u00F3n del contenido
es.caib.rolsac2.procServ.accion.PV.ca=Es sol�licita la publicaci\u00F3 del contingut
es.caib.rolsac2.procServ.accion.PT.es=Se solicita cerrar el contenido
es.caib.rolsac2.procServ.accion.PT.ca=Es sol�licita tancar el contigut
es.caib.rolsac2.procServ.accion.T.es=El contenido est\u00E1 cerrado
es.caib.rolsac2.procServ.accion.T.ca=El contingut est\u00E0 tancat
es.caib.rolsac2.procServ.accion.M.es=Se vuelve a enviar a modificaci\u00F3n
es.caib.rolsac2.procServ.accion.M.ca=Es torna a enviar a modificaci\u00F3
es.caib.rolsac2.procServ.accion.P.es=El contenido est\u00E1 publicado
es.caib.rolsac2.procServ.accion.P.ca=El contingut s'ha publicat

#Cuando se crea una UA desde 0, es lo que se muestra en el campo comun de la UA (luego en los procedimientos se utiliza lo de la entidad editada)
es.caib.rolsac2.comun.ua.es=El \u00F3rgano competente por materia
es.caib.rolsac2.comun.ua.ca=L'\u00F2rgan competent per mat\u00E8ria


#PLG PDU
plg.pdu.url=
plg.pdu.usr=
plg.pdu.pwd=
plg.pdu.activopdu=
#PLG SOLR
plg.indexacion.solrUrl=
plg.indexacion.solrUsr=
plg.indexacion.solrPwd=
plg.indexacion.solrIdx=
plg.indexacion.elasticUrl=
plg.indexacion.elasticUsr=
plg.indexacion.elasticPwd=
#PLG EMAIL
plg.email.jndi=
#PLG SIA
plg.sia.url=
plg.sia.activosia=
#PLG DIR3
plg.dir3.url=
plg.dir3.usr=
plg.dir3.pwd=
#PLG TRADUCCION
plg.traduccion.url=
plg.traduccion.usr=
plg.traduccion.pwd=
#PLG BOLETIN. Toda su INFO es publica, asi que no hace falta añadir ningún cambio

# BACKEND END

## API INTERNA START
## API INTERNA END

## API EXTERNA START
## API EXTERNA END