CREATE TABLESPACE ROLSAC2_DADES
    DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/rolsac2_dades.dbf' 
    SIZE 100M 
    AUTOEXTEND ON NEXT 100M
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ROLSAC2_INDEX
    DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/rolsac2_index.dbf' 
    SIZE 100M 
    AUTOEXTEND ON NEXT 100M
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ROLSAC2_LOB
    DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/rolsac2_lob.dbf' 
    SIZE 100M 
    AUTOEXTEND ON NEXT 100M
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;