-- De momento, no hay datos iniciales
/* Entidad por defecto */
Insert into ROLSAC2.RS2_ENTIDA (ENTI_CODIGO,ENTI_IDENTI,ENTI_ACTIVA,ENTI_ROLADE,ENTI_ROLADC,ENTI_ROLGES,ENTI_ROLINF,ENTI_LOGO, ENTI_IDIPER, ENTI_IDIDEF, ENTI_IDIOBL) values (RS2_ENTIDA_SEQ.NEXTVAL ,'GOIB','1','ROLADE','ROLADC','ROLGES','ROLINF',null, 'es;ca;', 'ca', 'es;ca;');

Insert into ROLSAC2.RS2_TRAENT (TREN_CODIGO,TREN_CODENT,TREN_IDIOMA,TREN_DESCRI, TREN_LOPDFI, TREN_LOPDDS, TREN_LOPDDR, TREN_UACOMU) values (RS2_TRAENT_SEQ.NEXTVAL,RS2_ENTIDA_SEQ.CURRVAL,'es','GOIB descenti es','Tramitació del procediment','El destinatari de la lopd','El dret de la lopd','Responsable lopd común');
Insert into ROLSAC2.RS2_TRAENT (TREN_CODIGO,TREN_CODENT,TREN_IDIOMA,TREN_DESCRI, TREN_LOPDFI, TREN_LOPDDS, TREN_LOPDDR, TREN_UACOMU) values (RS2_TRAENT_SEQ.NEXTVAL,RS2_ENTIDA_SEQ.CURRVAL,'ca','GOIB descenti ca','Tramitación del procedimiento','El destinatario de la lopd','El derecho de la lopd','Responsable lopd comú');


/*Usuario por defecto*/
Insert into ROLSAC2.RS2_USER (USER_CODIGO,USER_USER, USER_NOMBRE, USER_EMAIL) values (RS2_USER_SEQ.NEXTVAL,'rolsac2', 'nom usuari', 'rolsac2@info.com');
Insert into ROLSAC2.RS2_TRAUSER (TRUS_CODIGO, TRUS_CODUS, TRUS_IDIOMA, TRUS_OBSER) values (RS2_TRAUSER_SEQ.NEXTVAL, RS2_USER_SEQ.CURRVAL, 'es', 'Observaciones ES');
Insert into ROLSAC2.RS2_TRAUSER (TRUS_CODIGO, TRUS_CODUS, TRUS_IDIOMA, TRUS_OBSER) values (RS2_TRAUSER_SEQ.NEXTVAL, RS2_USER_SEQ.CURRVAL, 'ca', 'Observaciones CA');

/*UA por defecto*/
Insert into ROLSAC2.RS2_UNIADM (UNAD_CODIGO,UNAD_CODENTI,UNAD_TIPOUA,UNAD_UNADPADRE,UNAD_DIR3,UNAD_IDENTI,UNAD_TFNO,UNAD_FAX,UNAD_EMAIL,UNAD_DOMINI,UNAD_RSPNOM,UNAD_RSPSEX,UNAD_RSPEMA,UNAD_ORDEN,UNAD_VERSION)
values (RS2_UNIADM_SEQ.NEXTVAL,RS2_ENTIDA_SEQ.CURRVAL,null,null,'A04003003',null,null,null,null,null,null,null,null,'1','1');
Insert into ROLSAC2.RS2_TRAUNAD (TRUA_CODIGO,TRUA_CODUNAD,TRUA_IDIOMA,TRUA_NOMBRE,TRUA_PRESEN,TRUA_URLWEB,TRUA_ABREVI,TRUA_RSPCV) values (RS2_TRAUNAD_SEQ.NEXTVAL,RS2_UNIADM_SEQ.CURRVAL,'es','Gobierno de las Islas Baleares',null,null,null, EMPTY_CLOB());
Insert into ROLSAC2.RS2_TRAUNAD (TRUA_CODIGO,TRUA_CODUNAD,TRUA_IDIOMA,TRUA_NOMBRE,TRUA_PRESEN,TRUA_URLWEB,TRUA_ABREVI,TRUA_RSPCV) values (RS2_TRAUNAD_SEQ.NEXTVAL,RS2_UNIADM_SEQ.CURRVAL,'ca','Govern de les Illes Balears',null,null,null, EMPTY_CLOB());

Insert into ROLSAC2.RS2_USERUA (UAUS_CODUSER,UAUS_CODUA) values (RS2_USER_SEQ.CURRVAL,RS2_UNIADM_SEQ.CURRVAL);
Insert into ROLSAC2.RS2_USENTI (USEN_CODUSER,USEN_CODENTI) values (RS2_USER_SEQ.CURRVAL,RS2_ENTIDA_SEQ.CURRVAL);

/* Datos para inicio de procesos automáticos*/
insert into ROLSAC2.RS2_PROCES (PROCES_CODIGO, PROCES_CODENTI, PROCES_IDENTI, PROCES_DESCRI, proces_cron, proces_activo, proces_params) VALUES (RS2_PROCES_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'TEST', 'Proceso de prueba', null, 1, '[{"codigo":"valida","valor":"true"}]');
insert into ROLSAC2.RS2_PROCEX (procex_codigo, procex_instan, procex_fecha) VALUES ('MAESTRO', 'XXXX', to_date('1998/05/31:12:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'));
insert into ROLSAC2.RS2_PROCES (PROCES_CODIGO, PROCES_CODENTI, PROCES_IDENTI, PROCES_DESCRI, proces_cron, proces_activo, proces_params) VALUES (RS2_PROCES_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'SIA_PUNT', 'Proceso de lanzamiento puntual SIA', null, 1, '[{"codigo":"valida","valor":"true"}]');
insert into ROLSAC2.RS2_PROCES (PROCES_CODIGO, PROCES_CODENTI, PROCES_IDENTI, PROCES_DESCRI, proces_cron, proces_activo, proces_params) VALUES (RS2_PROCES_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'SOLR_PUNT', 'Proceso  de lanzamiento puntual SOLR', null, 1, '[{"codigo":"valida","valor":"true"}]');
insert into ROLSAC2.RS2_PROCES (PROCES_CODIGO, PROCES_CODENTI, PROCES_IDENTI, PROCES_DESCRI, proces_cron, proces_activo, proces_params) VALUES (RS2_PROCES_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'MIGRA_PUNT', 'Proceso  de lanzamiento puntual MIGRACION', null, 1, '[{"codigo":"valida","valor":"true"}]');

Insert into ROLSAC2.RS2_PLUGIN (PLUG_CODIGO, PLUG_CODENTI, PLUG_DESC, PLUG_CLASSNAME, PLUG_PROPS, PLUG_PREPRO, PLUG_TIPO)
VALUES (RS2_PLUGIN_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'Plugin de boletín', 'es.caib.rolsac2.commons.plugins.boletin.eboib.EboibPlugin',
        '[{"codigo":"eboibUrl","valor":"https://www.caib.es/eboibfront/","orden":null}, {"codigo":"tipoBoletin","valor":"1","orden":null}]',
        'pluginsib.boletin.eboib.', 'BOL');

Insert into ROLSAC2.RS2_PLUGIN (PLUG_CODIGO, PLUG_CODENTI, PLUG_DESC, PLUG_CLASSNAME, PLUG_PROPS, PLUG_PREPRO, PLUG_TIPO)
VALUES (RS2_PLUGIN_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'Plugin de traducción', 'es.caib.rolsac2.commons.plugins.traduccion.translatorib.TranslatorIBPlugin',
        '[{"codigo":"url","valor":"https://dev.caib.es/translatorib/api/services/traduccion/v1","orden":null},{"codigo":"usr","valor":"api-tib","orden":null},{"codigo":"pwd","valor":"XXXXXX","orden":null}]',
        'pluginsib.traduccion.translatorib.', 'TRA');

Insert into ROLSAC2.RS2_PLUGIN (PLUG_CODIGO, PLUG_CODENTI, PLUG_DESC, PLUG_CLASSNAME, PLUG_PROPS, PLUG_PREPRO, PLUG_TIPO)
VALUES (RS2_PLUGIN_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'Plugin de consulta al API REST DIR3CAIB', 'es.caib.rolsac2.commons.plugins.dir3.caib.Dir3CaibRestPlugin',
        '[{"codigo":"url","valor":"https://dev.caib.es/dir3caib/rest","orden":null},{"codigo":"usr","valor":"$sistra_dir3caib","orden":null},{"codigo":"pwd","valor":"sistra_dir3caib","orden":null}]',
        'es.caib.rolsac2.pluginsib.dir3.caib.', 'DI3');

Insert into ROLSAC2.RS2_PLUGIN (PLUG_CODIGO, PLUG_CODENTI, PLUG_DESC, PLUG_CLASSNAME, PLUG_PROPS, PLUG_PREPRO, PLUG_TIPO)
VALUES (RS2_PLUGIN_SEQ.NEXTVAL, RS2_ENTIDA_SEQ.CURRVAL, 'Plugin de indexacion sia', 'es.caib.rolsac2.commons.plugins.sia.sia.SiaWSPlugin',
        '[{"codigo":"url","valor":"http://pre-sia2.redsara.es/axis2/services/wsSIAActualizarActuaciones","orden":null}]',
        'pluginsib.indexacion.sia.', 'SIA');


/** Los 3 tipos de publico objetivo basico que son 1.Ciudadano 2.Empresa 3.Administración . **/
INSERT INTO ROLSAC2.RS2_TIPOPUB(TPPO_CODIGO, TPPO_IDENTI, TPPO_EMPPUB)
VALUES (RS2_TIPOPUB_SEQ.NEXTVAL, 'CIUDADANO', 0);
INSERT INTO ROLSAC2.RS2_TRATPPO(TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
VALUES (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'es','Ciudadano');
INSERT INTO ROLSAC2.RS2_TRATPPO(TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
VALUES (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'ca','Ciutadà');

INSERT INTO ROLSAC2.RS2_TIPOPUB(TPPO_CODIGO, TPPO_IDENTI, TPPO_EMPPUB)
VALUES (RS2_TIPOPUB_SEQ.NEXTVAL, 'EMPRESA', 0);
INSERT INTO ROLSAC2.RS2_TRATPPO(TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
VALUES (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'es','Empresa');
INSERT INTO ROLSAC2.RS2_TRATPPO(TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
VALUES (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'ca','Empresa');

INSERT INTO ROLSAC2.RS2_TIPOPUB(TPPO_CODIGO, TPPO_IDENTI, TPPO_EMPPUB)
VALUES (RS2_TIPOPUB_SEQ.NEXTVAL, 'ADMINISTRACION', 0);
INSERT INTO ROLSAC2.RS2_TRATPPO(TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
VALUES (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'es','Administración');
INSERT INTO ROLSAC2.RS2_TRATPPO(TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
VALUES (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'ca','Administració');

INSERT INTO ROLSAC2.RS2_TIPOPUB(TPPO_CODIGO, TPPO_IDENTI, TPPO_EMPPUB)
VALUES (RS2_TIPOPUB_SEQ.NEXTVAL, 'EMPLEOPUBLICO', 0);
INSERT INTO ROLSAC2.RS2_TRATPPO(TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
VALUES (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'es','Empleo público');
INSERT INTO ROLSAC2.RS2_TRATPPO(TRTP_CODIGO, TRTP_CODTPPO, TRTP_IDIOMA, TRTP_DESCRI)
VALUES (RS2_TRATPPO_SEQ.NEXTVAL, RS2_TIPOPUB_SEQ.CURRVAL, 'ca','Ocupació pública');

/** Las materias cogiendo de la tabla ROLSAC1 RSC_SIAMAT **/
INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'AGRICULTURA_PESCA', 21);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Agricultura, Ganadería; Pesca y Alimentación');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Agricultura, Ramaderia; Pesca i Alimentació');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'BECAS_AYUDAS_PREM', 22);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Becas, Ayudas y Premios');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Beques, Ajudes i Premis');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'CONSUM', 23);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Consumo');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Consum');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'ECONOMIA_PATRIMONIO', 26);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Economía y Patrimonio del Estado');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Economia i Patrimoni de lEstat');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'EDUCACION_FORMACION', 27);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Educación y formación');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Educació i formació');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'EMPRESES', 28);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Empresas');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Empreses');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'ENERGIA_INDUSTRIAS', 29);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Energía e Industria');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Energia i Indústria');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'IMPUESTOS_OTROS', 30);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Impuestos y otros tributos');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Imposats i altres tributs');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'JUSTICIA', 31);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Justicia');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Justicia');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'MEDIO_AMBIENTE', 32);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Medio Ambiente');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Medi Ambient');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'PENSIONES', 33);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Pensiones');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Pensions');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'RELACIONES_ADMIN', 34);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Relaciones con la Administración ');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Relacions amb lAdministració ');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'SALUD', 35);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Salud ');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Salut ');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'EMPLEO_SEGSOCIAL', 37);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Empleo y Seguridad social');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Ocupació i Seguretat social');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'TRAFICO_TRANSPORTES', 38);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Tráfico y Transportes');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Trànsit i Transports');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'VIVIENDA_URBANISMO', 39);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Vivienda y Urbanismo');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Habitatge i Urbanisme');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'ASOCIACIONES_FUNDACIONES', 40);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Asociaciones, Fundaciones y otras Entidades');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Associacions, Fundacions i altres Entitats');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'ACCION_EXTERIOR', 41);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Acción exterior');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Acció exterior');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'CULTURA', 42);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Cultura');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Cultura');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'DEPORTES', 43);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Deportes');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Deportes');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'CIUDADANIA_NACIONALIDAD', 44);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Ciudadanía y nacionalidad');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Ciutadania i nacionalitat');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'ESTADISTICAS', 45);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Estadísticas');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Estadístiques');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'PARTICIPACION_CIUDADANA', 46);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Participación e iniciativa ciudadana');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Participació i iniciativa ciutadana');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'PROTECCION_CIVIL', 47);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Protección Civil, Seguridad Ciudadana y Defensa Nacional');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Protecció Civil, Seguretat Ciutadana i Defensa Nacional');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'RELACIONES_ADMINSTRACIONES', 48);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Relaciones entre Administraciones Públicas');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Relacions entre Administracions Públiques');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'TECNOLOGIA_INVESTIGACION', 49);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Tecnología, Investigación  e Innovación');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Tecnologia, Recerca i Innovació');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'TELECOMUNICACION_INFORMACION', 50);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Telecomunicaciones y Sociedad de la Información');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Telecomunicacions i Societat de la Informació');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'TURISMO_OCIO', 51);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Turismo, ocio y tiempo libre');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Turisme, oci i temps lliure');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'SERVICIOS_SOCIALES', 52);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Servicios Sociales e Igualdad');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Serveis Socials i Igualtat');

INSERT INTO ROLSAC2.RS2_TIPOMSI(TPMS_CODIGO, TPMS_IDENTI, TPMS_CODSIA)
VALUES (RS2_TIPOMSI_SEQ.NEXTVAL, 'COMUNICACION', 53);
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'es', 'Comunicación');
INSERT INTO ROLSAC2.RS2_TRATPMS(TRTI_CODIGO, TRTI_CODTPMS, TRTI_IDIOMA, TRTI_DESCRI)
VALUES (RS2_TRATPMS_SEQ.NEXTVAL, RS2_TIPOMSI_SEQ.CURRVAL, 'ca', 'Comunicació');

/** Los sexos segun rolsac1 **/
INSERT INTO ROLSAC2.RS2_TIPOSEX(TPSX_CODIGO, TPSX_IDENTI)
VALUES (RS2_TIPOSEX_SEQ.NEXTVAL, 'MASCULINO');
INSERT INTO ROLSAC2.RS2_TRATPSX(TRTS_CODIGO, TRTS_CODTPSX, TRTS_IDIOMA, TRTS_DESCRI)
VALUES (RS2_TRATPSX_SEQ.NEXTVAL, RS2_TIPOSEX_SEQ.CURRVAL, 'es', 'Masculino');
INSERT INTO ROLSAC2.RS2_TRATPSX(TRTS_CODIGO, TRTS_CODTPSX, TRTS_IDIOMA, TRTS_DESCRI)
VALUES (RS2_TRATPSX_SEQ.NEXTVAL, RS2_TIPOSEX_SEQ.CURRVAL, 'ca', 'Masculí');

INSERT INTO ROLSAC2.RS2_TIPOSEX(TPSX_CODIGO, TPSX_IDENTI)
VALUES (RS2_TIPOSEX_SEQ.NEXTVAL, 'FEMENINO');
INSERT INTO ROLSAC2.RS2_TRATPSX(TRTS_CODIGO, TRTS_CODTPSX, TRTS_IDIOMA, TRTS_DESCRI)
VALUES (RS2_TRATPSX_SEQ.NEXTVAL, RS2_TIPOSEX_SEQ.CURRVAL, 'es', 'Femenino');
INSERT INTO ROLSAC2.RS2_TRATPSX(TRTS_CODIGO, TRTS_CODTPSX, TRTS_IDIOMA, TRTS_DESCRI)
VALUES (RS2_TRATPSX_SEQ.NEXTVAL, RS2_TIPOSEX_SEQ.CURRVAL, 'ca', 'Femení');

/** Los tipos de normativas. **/
INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (1,'LEY', 7,	2);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 1,'Ley','es');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 1,'Llei','ca');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (2,'DECRETO', 19, 5225);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 2,'Decreto','es');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 2,'Decret','ca');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (3,'REAL_DECRETO', 10, null);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 3,'Real Decreto','es');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 3,'Reial Decret','ca');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (4,'ORDEN',	11,	5227);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 4,'Orden','es');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 4,'Ordre','ca');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (5,'REAL_DECRETO_LEY', 9, null);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 5,'Reial Decret Llei','ca');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 5,'Real Decreto Ley','es');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (6,'REAL_DECRETO_LEG',	8,null);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 6,'Real Decreto Legislativo','ca');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 6,'Reial Decret Legislatiu','es');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (7,'DECRETO_LEY', 9,29);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 7,'Decreto Ley','es');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 7,'Decret Llei','ca');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (8,'DECRETO_LEG',	22,	31);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 8,'Decret Legislatiu','ca');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 8,'Decreto Legislativo','es');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (12,'ORDEN_MINISTERIAL', 11,null);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 12,'Ordre Ministerial','ca');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 12,'Ordre Ministerial','es');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (20,'DECRETO_PRESIDENTE',19,184);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 20,'Decret del president','ca');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 20,'Decreto del presidente','es');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (1707912,'REGLAMENTO',	18, null);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 1707912,'Reglamento','es');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 1707912,'Reglament','ca');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (2724592,'DIRECTIVA_EUROPEA', null, null);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 2724592,'Directiva Europea','es');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 2724592,'Directiva Europea','ca');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (2724593,'LEY_ORGANICA', null, null);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 2724593,'Llei Orgànica','ca');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 2724593,'Ley Orgánica','es');

INSERT INTO RS2_TIPONOR(TPNO_CODIGO , TPNO_IDENTI, TPNO_CODSIA, TPNO_IDBOIB) VALUES (2724594,'REGLAMENTO_EUROPEO', null, null);
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 2724594,'Reglament Europeu','ca');
INSERT INTO RS2_TRATPNO(TRTN_CODIGO,TRTN_CODTPNO,TNTR_DESCR,TRTN_IDIOMA) VALUES (RS2_TRATPNO_SEQ.NEXTVAL, 2724594,'Reglamento Europeo','es');

/** TIPO BOLETIN **/
INSERT INTO RS2_BOLETI (BOLE_CODIGO, BOLE_IDENTI, BOLE_NOMBRE, BOLE_URL ) VALUES (RS2_BOLETI_SEQ.NEXTVAL/*1*/, 'BOIB', 'BOIB', 'http://boib.caib.es/pdf/2009015/mp2.pdf' );
INSERT INTO RS2_BOLETI (BOLE_CODIGO, BOLE_IDENTI, BOLE_NOMBRE, BOLE_URL ) VALUES (RS2_BOLETI_SEQ.NEXTVAL/*21*/, 'BOE', 'BOE', null );
INSERT INTO RS2_BOLETI (BOLE_CODIGO, BOLE_IDENTI, BOLE_NOMBRE, BOLE_URL ) VALUES (RS2_BOLETI_SEQ.NEXTVAL/*2724696*/, 'DOUE', 'DOUE', null);





