/** INDICE EN TRAMITES CON LAS FECHAS **/
CREATE INDEX RS2_PRCTRAM_IDX on RS2_PRCTRM (PRTA_FECINI);
CREATE INDEX RS2_PRCTRAM_IDX2 on RS2_PRCTRM (PRTA_FECCIE);

/** INDICES EN PROCEDIMIENTOS. **/
CREATE INDEX RS2_PRCWF_IDX ON RS2_PRCWF(PRWF_FECPUB);
CREATE INDEX RS2_PRCWF_IDX2 ON RS2_PRCWF(PRWF_FECCAD);
CREATE INDEX RS2_PROC_IDX ON RS2_PROC(PROC_SIACOD);

/** INDICES EN NORMATIVAS. **/
CREATE INDEX RS2_NORMA_IDX ON RS2_NORMA(NORM_VIGENT);

/** INDICES EN UNIDADES ADMINISTRATIVAS. **/
CREATE INDEX RS2_UNIADM_IDX ON RS2_UNIADM(UNAD_DIR3);