/** ANYADIMOS LA OPCION DE LOGO EN LA ENTIDAD **/
ALTER TABLE RS2_ENTIDA ADD ENTI_LOGO2 NUMBER(10) NULL;
COMMENT ON COLUMN RS2_ENTIDA.ENTI_LOGO2 IS 'LOGO APLICACION';
ALTER TABLE "RS2_ENTIDA"
	ADD CONSTRAINT "RS2_ENTIDA_LOGO2_FK"
		FOREIGN KEY (ENTI_LOGO2) REFERENCES RS2_FICEXT(FIE_CODIGO);

/** ANYADIMOS A LA ENTIDAD EL CAMPO LOPD COMUN **/
ALTER TABLE RS2_TRAENT ADD TREN_LOPDCO VARCHAR2(4000 CHAR) NULL;
COMMENT ON COLUMN "RS2_TRAENT"."TREN_LOPDCO" IS 'LOPD COMUN';