create or replace FUNCTION "CHECK_CUELGA_UA" 
(
  CODIGO_UA_INICIAL IN NUMBER 
, CODIGO_UA_RAIZ IN NUMBER 
) RETURN BOOLEAN AS 
  SEGUIR BOOLEAN := true; 
  REPETICIONES NUMBER:=0;
  CODIGO_UA NUMBER;      
  CODIGO_PADRE NUMBER;      
BEGIN
  CODIGO_UA := CODIGO_UA_INICIAL;
  WHILE SEGUIR AND REPETICIONES <= 10
  LOOP  
     SELECT UNA_CODUNA
        INTO CODIGO_PADRE
        FROM RSC_UNIADM@ROLSAC
        WHERE UNA_CODI = CODIGO_UA;

     IF CODIGO_PADRE IS NULL
     THEN
        IF CODIGO_UA = CODIGO_UA_RAIZ
        THEN
            RETURN TRUE;
        ELSE
            RETURN FALSE;
        END IF;
     ELSE
        CODIGO_UA := CODIGO_PADRE;
     END IF;

     REPETICIONES := REPETICIONES +1;
  END LOOP;
  RETURN FALSE;
END CHECK_CUELGA_UA;