

/** UAS, USUARIOS, TRADUCCIONES Y RELACIONES ENTRE ELLOS **/
CREATE OR REPLACE SYNONYM R1_UNIADM FOR ROLSAC1.RSC_UNIADM;
CREATE OR REPLACE SYNONYM R1_USUARIO FOR ROLSAC1.RSC_USUARI;
CREATE OR REPLACE SYNONYM R1_UNIADM_TRAD FOR ROLSAC1.RSC_TRAUNA;
CREATE OR REPLACE SYNONYM R1_UNIADM_USU FOR ROLSAC1.RSC_UNAUSU;
CREATE OR REPLACE SYNONYM R1_UNIADM_NORM FOR ROLSAC1.RSC_UNANOR;
CREATE OR REPLACE SYNONYM R1_UNIADM_MATE FOR ROLSAC1.RSC_UNAMAT;

/** NORMATIVAS Y TRADUCCIONES **/
CREATE OR REPLACE SYNONYM R1_NORMAT FOR ROLSAC1.RSC_NORMAT;
CREATE OR REPLACE SYNONYM R1_NORMAT_TRAD FOR ROLSAC1.RSC_TRANOR;
CREATE OR REPLACE SYNONYM R1_NORMAT_AFECTA FOR ROLSAC1.RSC_AFECTA;
CREATE OR REPLACE SYNONYM R1_NORMAT_DOC FOR ROLSAC1.RSC_DOCNOR;
CREATE OR REPLACE SYNONYM R1_NORMAT_DOC_TRAD FOR ROLSAC1.RSC_TRADNR;

/** MATERIAS **/
CREATE OR REPLACE SYNONYM R1_MATERIAS FOR ROLSAC1.RSC_MATERI;

/** PROCEDIMIENTOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS FOR ROLSAC1.RSC_PROCED;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TRAD FOR ROLSAC1.RSC_TRAPRO;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_NORM FOR ROLSAC1.RSC_PRONOR;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_POBJ FOR ROLSAC1.RSC_POBPRO;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_MATE FOR ROLSAC1.RSC_PROMAT;
CREATE OR REPLACE SYNONYM R1_TRAMITES FOR ROLSAC1.RSC_TRAMIT;
CREATE OR REPLACE SYNONYM R1_TRAMITES_TRAD FOR ROLSAC1.RSC_TRATRA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_DOC FOR ROLSAC1.RSC_DOCUME;
CREATE OR REPLACE SYNONYM R1_TRAMITES_DOC FOR ROLSAC1.RSC_DOCTRA;
CREATE OR REPLACE SYNONYM R1_TRAMITES_DOC_TRAD FOR ROLSAC1.RSC_TRADOCTRA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_DOC_TRAD FOR ROLSAC1.RSC_TRADOC;

/** SERVICIOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE OR REPLACE SYNONYM R1_SERVICIOS FOR ROLSAC1.RSC_SERVIC;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_TRAD FOR ROLSAC1.RSC_TRASER;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_NORM FOR ROLSAC1.RSC_SERNOR;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_POBJ FOR ROLSAC1.RSC_POBSER;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_MATE FOR ROLSAC1.RSC_SERMAT;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_DOC FOR ROLSAC1.RSC_DOCSER;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_DOC_TRAD FOR ROLSAC1.RSC_TRADSR;

/** AUDITORIAS **/
CREATE OR REPLACE SYNONYM  R1_PROCEDIMIENTOS_AUDITO FOR ROLSAC1.RSC_AUDITO;
CREATE OR REPLACE SYNONYM  R1_PROCEDIMIENTOS_HISTOR FOR ROLSAC1.RSC_HISTOR;

/** ARCHIVOS. **/
CREATE OR REPLACE SYNONYM R1_ARCHIV FOR ROLSAC1.RSC_ARCHIV;
