

/** UAS, USUARIOS, TRADUCCIONES Y RELACIONES ENTRE ELLOS **/
CREATE OR REPLACE SYNONYM R1_UNIADM FOR RSC_UNIADM;
CREATE OR REPLACE SYNONYM R1_USUARIO FOR RSC_USUARI;
CREATE OR REPLACE SYNONYM R1_UNIADM_TRAD FOR RSC_TRAUNA;
CREATE OR REPLACE SYNONYM R1_UNIADM_USU FOR RSC_UNAUSU;
CREATE OR REPLACE SYNONYM R1_UNIADM_NORM FOR RSC_UNANOR;
CREATE OR REPLACE SYNONYM R1_UNIADM_MATE FOR RSC_UNAMAT;

/** NORMATIVAS Y TRADUCCIONES **/
CREATE OR REPLACE SYNONYM R1_NORMAT FOR RSC_NORMAT;
CREATE OR REPLACE SYNONYM R1_NORMAT_TRAD FOR RSC_TRANOR;
CREATE OR REPLACE SYNONYM R1_NORMAT_AFECTA FOR RSC_AFECTA;
CREATE OR REPLACE SYNONYM R1_NORMAT_DOC FOR RSC_DOCNOR;
CREATE OR REPLACE SYNONYM R1_NORMAT_DOC_TRAD FOR RSC_TRADNR;

/** MATERIAS **/
CREATE OR REPLACE SYNONYM R1_MATERIAS FOR RSC_MATERI;

/** PROCEDIMIENTOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS FOR RSC_PROCED;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TRAD FOR RSC_TRAPRO;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_NORM FOR RSC_PRONOR;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_POBJ FOR RSC_POBPRO;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_MATE FOR RSC_PROMAT;
CREATE OR REPLACE SYNONYM R1_TRAMITES FOR RSC_TRAMIT;
CREATE OR REPLACE SYNONYM R1_TRAMITES_TRAD FOR RSC_TRATRA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_DOC FOR RSC_DOCUME;
CREATE OR REPLACE SYNONYM R1_TRAMITES_DOC FOR RSC_DOCTRA;
CREATE OR REPLACE SYNONYM R1_TRAMITES_DOC_TRAD FOR RSC_TRADOCTRA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_DOC_TRAD FOR RSC_TRADOC;

/** SERVICIOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE OR REPLACE SYNONYM R1_SERVICIOS FOR RSC_SERVIC;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_TRAD FOR RSC_TRASER;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_NORM FOR RSC_SERNOR;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_POBJ FOR RSC_POBSER;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_MATE FOR RSC_SERMAT;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_DOC FOR RSC_DOCSER;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_DOC_TRAD FOR RSC_TRADSR;

/** AUDITORIAS **/
CREATE OR REPLACE SYNONYM  R1_PROCEDIMIENTOS_AUDITO FOR RSC_AUDITO;
CREATE OR REPLACE SYNONYM  R1_PROCEDIMIENTOS_HISTOR FOR RSC_HISTOR;

/** ARCHIVOS. **/
CREATE OR REPLACE SYNONYM R1_ARCHIV FOR RSC_ARCHIV;
