create or replace PROCEDURE "ACTIVAR_RESTRICCIONES_DOCS" 
AS 
    maximoId NUMBER;
    VALOR    NUMBER;
    VALOR_SEQ NUMBER;
BEGIN
 
    /** ACTIVAMOS LA FK DE ARCHIVOS CON DOCS **/
    EXECUTE IMMEDIATE ' ALTER TABLE "RS2_TRADOPR" ENABLE CONSTRAINT "RS2_TRADOPR_FICEXT_FK"';

END;