
/** UAS, USUARIOS, TRADUCCIONES Y RELACIONES ENTRE ELLOS **/
GRANT SELECT ON RSC_UNIADM TO WWW_ROLSAC2;
GRANT SELECT ON RSC_USUARI TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRAUNA TO WWW_ROLSAC2;
GRANT SELECT ON RSC_UNAUSU TO WWW_ROLSAC2;
GRANT SELECT ON RSC_UNANOR TO WWW_ROLSAC2;
GRANT SELECT ON RSC_UNAMAT TO WWW_ROLSAC2;

/** NORMATIVAS Y TRADUCCIONES **/
GRANT SELECT ON RSC_NORMAT TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRANOR TO WWW_ROLSAC2;
GRANT SELECT ON RSC_AFECTA TO WWW_ROLSAC2;
GRANT SELECT ON RSC_DOCNOR TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRADNR TO WWW_ROLSAC2;

/** MATERIAS **/
GRANT SELECT ON RSC_MATERI TO WWW_ROLSAC2;

/** PROCEDIMIENTOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
GRANT SELECT ON RSC_PROCED TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRAPRO TO WWW_ROLSAC2;
GRANT SELECT ON RSC_PRONOR TO WWW_ROLSAC2;
GRANT SELECT ON RSC_POBPRO TO WWW_ROLSAC2;
GRANT SELECT ON RSC_PROMAT TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRAMIT TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRATRA TO WWW_ROLSAC2;
GRANT SELECT ON RSC_DOCUME TO WWW_ROLSAC2;
GRANT SELECT ON RSC_DOCTRA TO WWW_ROLSAC2; 
GRANT SELECT ON RSC_TRADOCTRA TO WWW_ROLSAC2; 
GRANT SELECT ON RSC_TRADOC TO WWW_ROLSAC2;
GRANT SELECT ON RSC_PROMSJ TO WWW_ROLSAC2;

/** AUDITORIAS **/
GRANT SELECT ON RSC_AUDITO TO WWW_ROLSAC2;
GRANT SELECT ON RSC_HISTOR TO WWW_ROLSAC2;

/** SERVICIOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
GRANT SELECT ON RSC_SERVIC TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRASER TO WWW_ROLSAC2;
GRANT SELECT ON RSC_SERNOR TO WWW_ROLSAC2;
GRANT SELECT ON RSC_POBSER TO WWW_ROLSAC2;
GRANT SELECT ON RSC_SERMAT TO WWW_ROLSAC2;
GRANT SELECT ON RSC_DOCSER TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRADSR TO WWW_ROLSAC2;

/** ARCHIVOS. **/
GRANT SELECT ON RSC_ARCHIV TO WWW_ROLSAC2;

/** taxas **/
GRANT SELECT ON RSC_TAXA TO WWW_ROLSAC2;
GRANT SELECT ON RSC_TRATAX TO WWW_ROLSAC2;