

/** UAS, USUARIOS, TRADUCCIONES Y RELACIONES ENTRE ELLOS **/
CREATE OR REPLACE SYNONYM R1_UNIADM FOR ROLSAC.RSC_UNIADM;
CREATE OR REPLACE SYNONYM R1_USUARIO FOR ROLSAC.RSC_USUARI;
CREATE OR REPLACE SYNONYM R1_UNIADM_TRAD FOR ROLSAC.RSC_TRAUNA;
CREATE OR REPLACE SYNONYM R1_UNIADM_USU FOR ROLSAC.RSC_UNAUSU;
CREATE OR REPLACE SYNONYM R1_UNIADM_NORM FOR ROLSAC.RSC_UNANOR;
CREATE OR REPLACE SYNONYM R1_UNIADM_MATE FOR ROLSAC.RSC_UNAMAT;

/** NORMATIVAS Y TRADUCCIONES **/
CREATE OR REPLACE SYNONYM R1_NORMAT FOR ROLSAC.RSC_NORMAT;
CREATE OR REPLACE SYNONYM R1_NORMAT_TRAD FOR ROLSAC.RSC_TRANOR;
CREATE OR REPLACE SYNONYM R1_NORMAT_AFECTA FOR ROLSAC.RSC_AFECTA;
CREATE OR REPLACE SYNONYM R1_NORMAT_DOC FOR ROLSAC.RSC_DOCNOR;
CREATE OR REPLACE SYNONYM R1_NORMAT_DOC_TRAD FOR ROLSAC.RSC_TRADNR;

/** MATERIAS **/
CREATE OR REPLACE SYNONYM R1_MATERIAS FOR ROLSAC.RSC_MATERI;

/** PROCEDIMIENTOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS FOR ROLSAC.RSC_PROCED;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TRAD FOR ROLSAC.RSC_TRAPRO;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_NORM FOR ROLSAC.RSC_PRONOR;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_POBJ FOR ROLSAC.RSC_POBPRO;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_MATE FOR ROLSAC.RSC_PROMAT;
CREATE OR REPLACE SYNONYM R1_TRAMITES FOR ROLSAC.RSC_TRAMIT;
CREATE OR REPLACE SYNONYM R1_TRAMITES_TRAD FOR ROLSAC.RSC_TRATRA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_DOC FOR ROLSAC.RSC_DOCUME;
CREATE OR REPLACE SYNONYM R1_TRAMITES_DOC FOR ROLSAC.RSC_DOCTRA;
CREATE OR REPLACE SYNONYM R1_TRAMITES_DOC_TRAD FOR ROLSAC.RSC_TRADOCTRA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_DOC_TRAD FOR ROLSAC.RSC_TRADOC;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_MENSAJES FOR ROLSAC.RSC_PROMSJ;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TAXAS FOR ROLSAC.RSC_TAXA;
CREATE OR REPLACE SYNONYM R1_PROCEDIMIENTOS_TAXAS_TRAD FOR ROLSAC.RSC_TRATAX;

/** SERVICIOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE OR REPLACE SYNONYM R1_SERVICIOS FOR ROLSAC.RSC_SERVIC;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_TRAD FOR ROLSAC.RSC_TRASER;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_NORM FOR ROLSAC.RSC_SERNOR;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_POBJ FOR ROLSAC.RSC_POBSER;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_MATE FOR ROLSAC.RSC_SERMAT;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_DOC FOR ROLSAC.RSC_DOCSER;
CREATE OR REPLACE SYNONYM R1_SERVICIOS_DOC_TRAD FOR ROLSAC.RSC_TRADSR;

/** AUDITORIAS **/
CREATE OR REPLACE SYNONYM  R1_PROCEDIMIENTOS_AUDITO FOR ROLSAC.RSC_AUDITO;
CREATE OR REPLACE SYNONYM  R1_PROCEDIMIENTOS_HISTOR FOR ROLSAC.RSC_HISTOR;

/** ARCHIVOS. **/
CREATE OR REPLACE SYNONYM R1_ARCHIV FOR ROLSAC.RSC_ARCHIV;
