create or replace FUNCTION "CHECK_CUELGA_UA_PROC" 
(
  CODIGO_UA_INICIAL IN NUMBER 
, CODIGO_UA_RAIZ IN NUMBER 
) RETURN NUMBER AS 
  SEGUIR NUMBER := 1; 
  REPETICIONES NUMBER:=0;
  CODIGO_UA NUMBER;      
  CODIGO_PADRE NUMBER;      
BEGIN
  CODIGO_UA := CODIGO_UA_INICIAL;
  WHILE SEGUIR = 1 AND REPETICIONES <= 10
  LOOP  
     SELECT UNA_CODUNA
        INTO CODIGO_PADRE
        FROM R1_UNIADM
        WHERE UNA_CODI = CODIGO_UA;

     IF CODIGO_PADRE IS NULL
     THEN
        IF CODIGO_UA = CODIGO_UA_RAIZ
        THEN
            RETURN 1;
        ELSE
            RETURN 0;
        END IF;
     ELSE
        CODIGO_UA := CODIGO_PADRE;
     END IF;

     REPETICIONES := REPETICIONES +1;
  END LOOP;
  RETURN 0;
END CHECK_CUELGA_UA_PROC;