create or replace PROCEDURE "DESACTIVAR_RESTRICCIONES_DOCS" 
AS 
    maximoId NUMBER;
    VALOR    NUMBER;
    VALOR_SEQ NUMBER;
BEGIN
 
    /** DESACTIVAMOS LA FK DE UA **/
    EXECUTE IMMEDIATE 'ALTER TABLE "RS2_TRADOPR" DISABLE CONSTRAINT RS2_TRADOPR_FICEXT_FK';
     

END;