
/** UAS, USUARIOS, TRADUCCIONES Y RELACIONES ENTRE ELLOS **/
GRANT SELECT ON RSC_UNIADM TO ROLSAC2;
GRANT SELECT ON RSC_USUARI TO ROLSAC2;
GRANT SELECT ON RSC_TRAUNA TO ROLSAC2;
GRANT SELECT ON RSC_UNAUSU TO ROLSAC2;
GRANT SELECT ON RSC_UNANOR TO ROLSAC2;
GRANT SELECT ON RSC_UNAMAT TO ROLSAC2;

/** NORMATIVAS Y TRADUCCIONES **/
GRANT SELECT ON RSC_NORMAT TO ROLSAC2;
GRANT SELECT ON RSC_TRANOR TO ROLSAC2;
GRANT SELECT ON RSC_AFECTA TO ROLSAC2;
GRANT SELECT ON RSC_DOCNOR TO ROLSAC2;
GRANT SELECT ON RSC_TRADNR TO ROLSAC2;

/** MATERIAS **/
GRANT SELECT ON RSC_MATERI TO ROLSAC2;

/** PROCEDIMIENTOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
GRANT SELECT ON RSC_PROCED TO ROLSAC2;
GRANT SELECT ON RSC_TRAPRO TO ROLSAC2;
GRANT SELECT ON RSC_PRONOR TO ROLSAC2;
GRANT SELECT ON RSC_POBPRO TO ROLSAC2;
GRANT SELECT ON RSC_PROMAT TO ROLSAC2;
GRANT SELECT ON RSC_TRAMIT TO ROLSAC2;
GRANT SELECT ON RSC_TRATRA TO ROLSAC2;
GRANT SELECT ON RSC_DOCUME TO ROLSAC2;
GRANT SELECT ON RSC_DOCTRA TO ROLSAC2; 
GRANT SELECT ON RSC_TRADOCTRA TO ROLSAC2; 
GRANT SELECT ON RSC_TRADOC TO ROLSAC2;

/** SERVICIOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
GRANT SELECT ON RSC_SERVIC TO ROLSAC2;
GRANT SELECT ON RSC_TRASER TO ROLSAC2;
GRANT SELECT ON RSC_SERNOR TO ROLSAC2;
GRANT SELECT ON RSC_POBSER TO ROLSAC2;
GRANT SELECT ON RSC_SERMAT TO ROLSAC2;
GRANT SELECT ON RSC_DOCSER TO ROLSAC2;
GRANT SELECT ON RSC_TRADSR TO ROLSAC2;

/** ARCHIVOS. **/
GRANT SELECT ON RSC_ARCHIV TO ROLSAC2;