

/** UAS, USUARIOS, TRADUCCIONES Y RELACIONES ENTRE ELLOS **/
CREATE SYNONYM R1_UNIADM FOR ROLSAC1.RSC_UNIADM;
CREATE SYNONYM R1_USUARIO FOR ROLSAC1.RSC_USUARI;
CREATE SYNONYM R1_UNIADM_TRAD FOR ROLSAC1.RSC_TRAUNA;
CREATE SYNONYM R1_UNIADM_USU FOR ROLSAC1.RSC_UNAUSU;
CREATE SYNONYM R1_UNIADM_NORM FOR ROLSAC1.RSC_UNANOR;

/** NORMATIVAS Y TRADUCCIONES **/
CREATE SYNONYM R1_NORMAT FOR ROLSAC1.RSC_NORMAT;
CREATE SYNONYM R1_NORMAT_TRAD FOR ROLSAC1.RSC_TRANOR;
CREATE SYNONYM R1_NORMAT_AFECTA FOR ROLSAC1.RSC_AFECTA;
CREATE SYNONYM R1_NORMAT_DOC FOR ROLSAC1.RSC_DOCNOR;
CREATE SYNONYM R1_NORMAT_DOC_TRAD FOR ROLSAC1.RSC_TRADNR;

/** MATERIAS **/
CREATE SYNONYM R1_MATERIAS FOR ROLSAC1.RSC_MATERI;

/** PROCEDIMIENTOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE SYNONYM R1_PROCEDIMIENTOS FOR ROLSAC1.RSC_PROCED;
CREATE SYNONYM R1_PROCEDIMIENTOS_TRAD FOR ROLSAC1.RSC_TRAPRO;
CREATE SYNONYM R1_PROCEDIMIENTOS_NORM FOR ROLSAC1.RSC_PRONOR;
CREATE SYNONYM R1_PROCEDIMIENTOS_POBJ FOR ROLSAC1.RSC_POBPRO;
CREATE SYNONYM R1_PROCEDIMIENTOS_MATE FOR ROLSAC1.RSC_PROMAT;
CREATE SYNONYM R1_TRAMITES FOR ROLSAC1.RSC_TRAMIT;
CREATE SYNONYM R1_TRAMITES_TRAD FOR ROLSAC1.RSC_TRATRA;
CREATE SYNONYM R1_PROCEDIMIENTOS_DOC FOR ROLSAC1.RSC_DOCUME;
CREATE SYNONYM R1_TRAMITES_DOC FOR ROLSAC1.RSC_DOCTRA;
CREATE SYNONYM R1_TRAMITES_DOC_TRAD FOR ROLSAC1.RSC_TRADOCTRA;
CREATE SYNONYM R1_PROCEDIMIENTOS_DOC_TRAD FOR ROLSAC1.RSC_TRADOC;

/** SERVICIOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE SYNONYM R1_SERVICIOS FOR ROLSAC1.RSC_SERVIC;
CREATE SYNONYM R1_SERVICIOS_TRAD FOR ROLSAC1.RSC_TRASER;
CREATE SYNONYM R1_SERVICIOS_NORM FOR ROLSAC1.RSC_SERNOR;
CREATE SYNONYM R1_SERVICIOS_POBJ FOR ROLSAC1.RSC_POBSER;
CREATE SYNONYM R1_SERVICIOS_MATE FOR ROLSAC1.RSC_SERMAT;
CREATE SYNONYM R1_SERVICIOS_DOC FOR ROLSAC1.RSC_DOCSER;
CREATE SYNONYM R1_SERVICIOS_DOC_TRAD FOR ROLSAC1.RSC_TRADSR;


/** ARCHIVOS. **/
CREATE SYNONYM R1_ARCHIV FOR ROLSAC1.RSC_ARCHIV;
