

/** UAS, USUARIOS, TRADUCCIONES Y RELACIONES ENTRE ELLOS **/
CREATE SYNONYM R1_UNIADM FOR ROLSAC.RSC_UNIADM;
CREATE SYNONYM R1_USUARIO FOR ROLSAC.RSC_USUARI;
CREATE SYNONYM R1_UNIADM_TRAD FOR ROLSAC.RSC_TRAUNA;
CREATE SYNONYM R1_UNIADM_USU FOR ROLSAC.RSC_UNAUSU;
CREATE SYNONYM R1_UNIADM_NORM FOR ROLSAC.RSC_UNANOR;

/** NORMATIVAS Y TRADUCCIONES **/
CREATE SYNONYM R1_NORMAT FOR ROLSAC.RSC_NORMAT;
CREATE SYNONYM R1_NORMAT_TRAD FOR ROLSAC.RSC_TRANOR;
CREATE SYNONYM R1_NORMAT_AFECTA FOR ROLSAC.RSC_AFECTA;

/** MATERIAS **/
CREATE SYNONYM R1_MATERIAS FOR ROLSAC.RSC_MATERI;

/** PROCEDIMIENTOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE SYNONYM R1_PROCEDIMIENTOS FOR ROLSAC.RSC_PROCED;
CREATE SYNONYM R1_PROCEDIMIENTOS_TRAD FOR ROLSAC.RSC_TRAPRO;
CREATE SYNONYM R1_PROCEDIMIENTOS_NORM FOR ROLSAC.RSC_PRONOR;
CREATE SYNONYM R1_PROCEDIMIENTOS_POBJ FOR ROLSAC.RSC_POBPRO;
CREATE SYNONYM R1_PROCEDIMIENTOS_MATE FOR ROLSAC.RSC_PROMAT;
CREATE SYNONYM R1_TRAMITES FOR ROLSAC.RSC_TRAMIT;
CREATE SYNONYM R1_TRAMITES_TRAD FOR ROLSAC.RSC_TRATRA;

/** SERVICIOS, TRADUCCIONES, NORMATIVAS, PUB. OBJETIVO Y MATERIAS **/
CREATE SYNONYM R1_SERVICIOS FOR ROLSAC.RSC_SERVIC;
CREATE SYNONYM R1_SERVICIOS_TRAD FOR ROLSAC.RSC_TRASER;
CREATE SYNONYM R1_SERVICIOS_NORM FOR ROLSAC.RSC_SERNOR;
CREATE SYNONYM R1_SERVICIOS_POBJ FOR ROLSAC.RSC_POBSER;
CREATE SYNONYM R1_SERVICIOS_MATE FOR ROLSAC.RSC_SERMAT;
