create or replace FUNCTION "OBTENER_PROF_UA" 
(
  CODIGO_UA_INICIAL IN NUMBER 
) RETURN NUMBER AS 
  SEGUIR BOOLEAN := true; 
  REPETICIONES NUMBER:=0;
  CODIGO_UA NUMBER;      
  CODIGO_PADRE NUMBER;  
  PROFUNDIDAD NUMBER;
BEGIN
  CODIGO_UA := CODIGO_UA_INICIAL;
  PROFUNDIDAD := 0;
  WHILE SEGUIR AND REPETICIONES <= 15
  LOOP  
     SELECT UNA_CODUNA
        INTO CODIGO_PADRE
        FROM R1_UNIADM
        WHERE UNA_CODI = CODIGO_UA;

     IF CODIGO_PADRE IS NULL
     THEN
        RETURN PROFUNDIDAD;
     ELSE
        CODIGO_UA := CODIGO_PADRE;
        PROFUNDIDAD := PROFUNDIDAD+1;
     END IF;

     REPETICIONES := REPETICIONES +1;
  END LOOP;
  RETURN PROFUNDIDAD;
END OBTENER_PROF_UA;