CREATE TABLESPACE ROLSAC2_DADES
DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/rolsac2_dades01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 100M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ROLSAC2_INDEX
DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/rolsac2_index01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 100M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ROLSAC2_LOB
DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/rolsac2_lob01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 100M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;