
package es.caib.rolsac2.commons.plugins.sia.sia.actualizar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsSIAActualizarActuaciones", targetNamespace = "http://www.map.es/sgca/actualizar")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsSIAActualizarActuaciones {


    /**
     * 
     * @param parameters
     * @return
     *     returns es.caib.rolsac2.commons.plugins.sia.sia.actualizar.EnviaSIA
     */
    @WebMethod(operationName = "actualizarSIA_v3_1", action = "http://www.map.es/sgca/actualizar/actualizarSIA_v3_1")
    @WebResult(name = "enviaSIA", targetNamespace = "http://www.map.es/sgca/actualizar/messages/v3_1/EnviaSIA", partName = "parameters")
    public EnviaSIA actualizarSIAV31(
        @WebParam(name = "paramSIA", targetNamespace = "http://www.map.es/sgca/actualizar/messages/v3_1/ParamSIA", partName = "parameters")
        ParamSIA parameters);

}
