package es.caib.rolsac2.commons.plugins.sia.sia.actualizar;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 */
@WebServiceClient(name = "wsSIAActualizarActuaciones", targetNamespace = "http://www.map.es/sgca/actualizar", wsdlLocation = "file:/R:/fuentes/rolsac2/rolsac2-commons/src/main/resources/wsdl/wsSIAActualizarActuaciones.wsdl")
public class WsSIAActualizarActuaciones_Service
        extends Service {

    private final static URL WSSIAACTUALIZARACTUACIONES_WSDL_LOCATION;
    private final static WebServiceException WSSIAACTUALIZARACTUACIONES_EXCEPTION;
    private final static QName WSSIAACTUALIZARACTUACIONES_QNAME = new QName("http://www.map.es/sgca/actualizar", "wsSIAActualizarActuaciones");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/R:/fuentes/rolsac2/rolsac2-commons/src/main/resources/wsdl/wsSIAActualizarActuaciones.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSIAACTUALIZARACTUACIONES_WSDL_LOCATION = url;
        WSSIAACTUALIZARACTUACIONES_EXCEPTION = e;
    }

    public WsSIAActualizarActuaciones_Service() {
        super(__getWsdlLocation(), WSSIAACTUALIZARACTUACIONES_QNAME);
    }

    public WsSIAActualizarActuaciones_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSIAACTUALIZARACTUACIONES_QNAME, features);
    }

    public WsSIAActualizarActuaciones_Service(URL wsdlLocation) {
        super(wsdlLocation, WSSIAACTUALIZARACTUACIONES_QNAME);
    }

    public WsSIAActualizarActuaciones_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSIAACTUALIZARACTUACIONES_QNAME, features);
    }

    public WsSIAActualizarActuaciones_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSIAActualizarActuaciones_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns WsSIAActualizarActuaciones
     */
    @WebEndpoint(name = "wsSIAActualizarActuacionesSOAP")
    public WsSIAActualizarActuaciones getWsSIAActualizarActuacionesSOAP() {
        return super.getPort(new QName("http://www.map.es/sgca/actualizar", "wsSIAActualizarActuacionesSOAP"), WsSIAActualizarActuaciones.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns WsSIAActualizarActuaciones
     */
    @WebEndpoint(name = "wsSIAActualizarActuacionesSOAP")
    public WsSIAActualizarActuaciones getWsSIAActualizarActuacionesSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.map.es/sgca/actualizar", "wsSIAActualizarActuacionesSOAP"), WsSIAActualizarActuaciones.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSIAACTUALIZARACTUACIONES_EXCEPTION != null) {
            throw WSSIAACTUALIZARACTUACIONES_EXCEPTION;
        }
        return WSSIAACTUALIZARACTUACIONES_WSDL_LOCATION;
    }

}
